### ISSUE TITLE
feat: Create a data-monitoring package [Data monitoring]

### ISSUE THREAD

**Issue by Saulrega** [Platzi-Master-C9/booking-services#103]
## Summary
We need to create the data-monitoring package for the backend into the monorepo using clean architecture.

## Acceptance Criteria:
- [ ] Create the package into the monorepo.
- [ ] Add configuration for eslint.
- [ ] Add configuration for testing using Jest.
- [ ] Apply clean architecture using a demo function.

**Comment by nazlonga** [comment]
PR of issue https://github.com/Platzi-Master-C9/booking-services/pull/124 was accepted. 
Issue completed.
