### ISSUE TITLE
chore: Create mongoDB driver [Data monitoring]

### ISSUE THREAD

**Issue by YaelRmz** [Platzi-Master-C9/booking-services#125]
# Summary
Create the MongoDB driver that will allow the connection for the data monitoring schemas.
# Acceptance Criteria:

- [x] Create a connection to MongoDB using the Mongoose library.
- [x] Create a logger using Winston library
- [x] Export the model and make it available.

**Comment by nazlonga** [comment]
@YaelRmz can you update the acceptance criteria, so we can see that it is already completed?
