### ISSUE TITLE
feat: Geolocation db getting place by lat,long query

### ISSUE THREAD

**Issue by emanuelalvaradog** [Platzi-Master-C9/booking-services#23]
## Summary:
We have to perform queries on the database based on the api requirements. This requirement will be getting an existing place based on its longitude and latitude.

## Acceptance Criteria:
- [ ] Write a MongoDB query that lets us get the only place that matches the longitude and latitude. 
- [ ] lat and long should be received.

**Comment by alexcamachogz** [comment]
Task already created.
