### ISSUE TITLE
feat: Implement Auth0 authentication on authentication package

### ISSUE THREAD

**Issue by G-zeus** [Platzi-Master-C9/booking-services#48]
## Summary

We need to create the authentication package for the backend into the monorepo.

## Acceptance criteria

- [x] Create the package into the monorepo
- [x] Install Auth0 library
- [x] Add eslint and configure it

**Comment by iam-oov** [comment]
Moved the "Authentication route must be redirect to auth0 login" criterion to [ISSUE_47](https://github.com/Platzi-Master-C9/booking-services/issues/47) to keep the issues organized.
