### ISSUE TITLE
feat: Create a booking package

### ISSUE THREAD

**Issue by elyager** [Platzi-Master-C9/booking-services#58]
## Summary
We need to create the booking package for the backend into the monorepo using clean architecture.

## Acceptance Criteria:
- [ ]  Create the package into the monorepo.
- [ ] Add configuration for eslint.
- [ ] Add configuration for testing using Jest.
- [ ]  Apply clean architecture using a demo function.

**Comment by artiko00** [comment]
Hi! i was worked in my repo, can you check if the fork is ok? @elyager please! thanks in advance!
https://github.com/artiko00/booking-services

**Comment by elyager** [comment]
Yes, the fork is ok @artiko00 any changes you do should be submitted as a PR, but the fork seems fine
