### ISSUE TITLE
[Admin Panel] feat: list of admins "GET /admin_panel/api/admins" end-point

### ISSUE THREAD

**Issue by jacorreamed** [Platzi-Master-C9/booking-services#83]
## Summary 💡
We have to create and endpoint  with the capability of list all admins and super admins applying filters and search fields described in the [RFC](https://github.com/jacorreamed/knowledge-base/blob/main/RFCs/accepted/0000-RFC-data-collection-and-data-schema-for-admin-panel.md#list-of-admins)

## Checklist ✅
- [ ] User can Retrieve a list of admins and super-admins
- [ ] User can apply a filter by profile
- [ ] User can apply a search by full_name
- [ ] To be able to use this endpoint user must be authenticated
- [ ] Response must be in JSON Format 
- [ ] Response code must according to [RFC](https://github.com/jacorreamed/knowledge-base/blob/main/RFCs/accepted/0000-RFC-data-collection-and-data-schema-for-admin-panel.md#list-of-admins) format
- [ ] Unit testing has to be implemented

**Comment by Emmanuel-Tvaz** [comment]
The PR was approved with the closure of this issue.
